//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSProjet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAllocation
    {
        public string EquipmentID { get; set; }
        public string ProjectID { get; set; }
        public int Duration { get; set; }
        public int Qty { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Project Project { get; set; }
    }
}
