//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSProjet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRate
    {
        public JobRate()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public string JobTitle { get; set; }
        public decimal Rate { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
