//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSProjet.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MACBuildersEntities : DbContext
    {
        public MACBuildersEntities()
            : base("name=MACBuildersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Clients { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<EquipmentAllocation> EquipmentAllocations { get; set; }
        public DbSet<JobRate> JobRates { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectPayment> ProjectPayments { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<WorkerAllocation> WorkerAllocations { get; set; }
    }
}
