//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSProjet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.EquipmentAllocations = new HashSet<EquipmentAllocation>();
            this.ProjectPayments = new HashSet<ProjectPayment>();
            this.WorkerAllocations = new HashSet<WorkerAllocation>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string BusinessName { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal ConsultantFee { get; set; }
        public decimal PersonnelCost { get; set; }
        public string ProjectConsultant { get; set; }
        public string ProjectManager { get; set; }
        public string Client { get; set; }
        public string status { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<EquipmentAllocation> EquipmentAllocations { get; set; }
        public virtual ICollection<ProjectPayment> ProjectPayments { get; set; }
        public virtual ICollection<WorkerAllocation> WorkerAllocations { get; set; }
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
