//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMSProjet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserManagement
    {
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string UserCategory { get; set; }
    }
}
